package web

// Code generated by scaffold; DO NOT EDIT.

import (
	"net/http"
)

func registerRoutes(mux *http.ServeMux) {
	// Auth routes (no auth required)
	mux.HandleFunc("/login", handleLogin)
	mux.HandleFunc("/logout", handleLogout)

	// Existing routes
	mux.HandleFunc("/attendance", handleGetAttendanceGetAttendanceToday)
	mux.HandleFunc("/checkin", handlePostCheckinCheckInMember)
	mux.HandleFunc("/checkin/form", handleGetCheckInForm)
	mux.HandleFunc("/injuries", handlePostInjuriesReportInjury)
	mux.HandleFunc("/injuries/form", handleGetInjuryForm)
	mux.HandleFunc("/members", handleMembers)
	mux.HandleFunc("/members/profile", handleGetMemberProfile)
	mux.HandleFunc("/members/register", handleGetMembersRegisterForm)
	mux.HandleFunc("/waivers", handlePostWaiversSignWaiver)
	mux.HandleFunc("/waivers/form", handleGetWaiverForm)

	// Layer 1a API routes
	mux.HandleFunc("/api/members/search", handleMemberSearch)
	mux.HandleFunc("/api/members/archive", handleArchiveMember)
	mux.HandleFunc("/api/members/restore", handleRestoreMember)
	mux.HandleFunc("/api/guest/checkin", handleGuestCheckIn)
	mux.HandleFunc("/api/classes/today", handleTodaysClasses)
	mux.HandleFunc("/api/kiosk/launch", handleKioskLaunch)
	mux.HandleFunc("/api/kiosk/exit", handleKioskExit)

	// Layer 1b API routes
	mux.HandleFunc("/api/training-log", handleGetTrainingLog)
	mux.HandleFunc("/api/members/inactive", handleGetInactiveMembers)
	mux.HandleFunc("/api/notices", handleNotices)
	mux.HandleFunc("/api/grading/proposals", handleGradingProposals)
	mux.HandleFunc("/api/messages", handleMessages)
	mux.HandleFunc("/api/observations", handleObservations)

	// Admin CRUD API routes
	mux.HandleFunc("/api/schedules", handleSchedules)
	mux.HandleFunc("/api/holidays", handleHolidays)
	mux.HandleFunc("/api/terms", handleTerms)
	mux.HandleFunc("/api/accounts", handleAccounts)
	mux.HandleFunc("/api/accounts/role", handleChangeRole)

	// Dashboard & Kiosk
	mux.HandleFunc("/dashboard", handleDashboard)
	mux.HandleFunc("/kiosk", handleKioskPage)

	// Admin management pages
	mux.HandleFunc("/admin/schedules", handleAdminSchedulesPage)
	mux.HandleFunc("/admin/holidays", handleAdminHolidaysPage)
	mux.HandleFunc("/admin/terms", handleAdminTermsPage)
	mux.HandleFunc("/admin/accounts", handleAdminAccountsPage)
	mux.HandleFunc("/admin/notices", handleAdminNoticesPage)
	mux.HandleFunc("/admin/grading", handleAdminGradingPage)
	mux.HandleFunc("/admin/inactive", handleAdminInactivePage)
	mux.HandleFunc("/admin/milestones", handleAdminMilestonesPage)

	// Member pages
	mux.HandleFunc("/training-log", handleTrainingLogPage)
	mux.HandleFunc("/messages", handleMessagesPage)

	// Class types API
	mux.HandleFunc("/api/class-types", handleClassTypes)

	// Layer 1b workflow routes
	mux.HandleFunc("/api/notices/publish", handleNoticePublish)
	mux.HandleFunc("/api/notices/edit", handleNoticeEdit)
	mux.HandleFunc("/api/notices/pin", handleNoticePin)
	mux.HandleFunc("/api/grading/proposals/decide", handleGradingDecide)
	mux.HandleFunc("/api/grading/config", handleGradingConfig)
	mux.HandleFunc("/api/grading/readiness", handleGradingReadiness)
	mux.HandleFunc("/api/training-goals", handleTrainingGoals)
	mux.HandleFunc("/api/milestones", handleMilestones)
	mux.HandleFunc("/api/messages/read", handleMessageRead)

	// Layer 2: Spine API routes
	mux.HandleFunc("/api/themes", handleThemes)
	mux.HandleFunc("/api/clips", handleClips)
	mux.HandleFunc("/api/clips/promote", handleClipPromote)

	// Layer 2: Spine pages
	mux.HandleFunc("/themes", handleThemesPage)
	mux.HandleFunc("/library", handleLibraryPage)

	// DevMode routes (admin-only impersonation)
	mux.HandleFunc("/api/devmode/impersonate", handleDevModeImpersonate)
	mux.HandleFunc("/api/devmode/restore", handleDevModeRestore)
}
