package web

// Code generated by scaffold; DO NOT EDIT.

import (
	"net/http"
)

func registerRoutes(mux *http.ServeMux) {
	// Auth routes (no auth required)
	mux.HandleFunc("/login", handleLogin)
	mux.HandleFunc("/logout", handleLogout)
	mux.HandleFunc("/change-password", handleChangePassword)
	mux.HandleFunc("/activate", handleActivatePage)
	mux.HandleFunc("/api/activate", handleActivateAccount)
	mux.HandleFunc("/api/admin/resend-activation", handleResendActivation)

	// Existing routes
	mux.HandleFunc("/attendance", handleGetAttendanceGetAttendanceToday)
	mux.HandleFunc("/checkin", handlePostCheckinCheckInMember)
	mux.HandleFunc("/checkin/form", handleGetCheckInForm)
	mux.HandleFunc("/injuries", handlePostInjuriesReportInjury)
	mux.HandleFunc("/injuries/form", handleGetInjuryForm)
	mux.HandleFunc("/members", handleMembers)
	mux.HandleFunc("/members/profile", handleGetMemberProfile)
	mux.HandleFunc("/members/register", handleGetMembersRegisterForm)
	mux.HandleFunc("/waivers", handlePostWaiversSignWaiver)
	mux.HandleFunc("/waivers/form", handleGetWaiverForm)

	// Layer 1a API routes
	mux.HandleFunc("/api/members/search", handleMemberSearch)
	mux.HandleFunc("/api/members/archive", handleArchiveMember)
	mux.HandleFunc("/api/members/restore", handleRestoreMember)
	mux.HandleFunc("/api/guest/checkin", handleGuestCheckIn)
	mux.HandleFunc("/api/attendance/member", handleMemberAttendanceToday)
	mux.HandleFunc("/api/attendance/undo", handleUndoCheckIn)
	mux.HandleFunc("/api/attendance/checkout", handleCheckOut)
	mux.HandleFunc("/api/estimated-hours", handleEstimatedHours)
	mux.HandleFunc("/api/estimated-hours/check-overlap", handleEstimatedHoursCheckOverlap)
	mux.HandleFunc("/api/self-estimates", handleSelfEstimates)
	mux.HandleFunc("/api/self-estimates/pending", handleSelfEstimatesPending)
	mux.HandleFunc("/api/self-estimates/review", handleSelfEstimatesReview)
	mux.HandleFunc("/api/classes/today", handleTodaysClasses)
	mux.HandleFunc("/api/kiosk/launch", handleKioskLaunch)
	mux.HandleFunc("/api/kiosk/exit", handleKioskExit)

	// Layer 1b API routes
	mux.HandleFunc("/api/training-log", handleGetTrainingLog)
	mux.HandleFunc("/api/members/inactive", handleGetInactiveMembers)
	mux.HandleFunc("/api/notices", handleNotices)
	mux.HandleFunc("/api/grading/proposals", handleGradingProposals)
	mux.HandleFunc("/api/messages", handleMessages)
	mux.HandleFunc("/api/observations", handleObservations)

	// Admin CRUD API routes
	mux.HandleFunc("/api/schedules", handleSchedules)
	mux.HandleFunc("/api/holidays", handleHolidays)
	mux.HandleFunc("/api/terms", handleTerms)
	mux.HandleFunc("/api/accounts", handleAccounts)
	mux.HandleFunc("/api/accounts/role", handleChangeRole)
	mux.HandleFunc("/api/admin/feature-flags", handleAdminFeatureFlags)
	mux.HandleFunc("/api/admin/beta-testers", handleAdminBetaTesters)

	// Dashboard & Kiosk
	mux.HandleFunc("/dashboard", handleDashboard)
	mux.HandleFunc("/kiosk", handleKioskPage)

	// Admin management pages
	mux.HandleFunc("/admin/schedules", handleAdminSchedulesPage)
	mux.HandleFunc("/admin/class-types", handleAdminClassTypesPage)
	mux.HandleFunc("/admin/holidays", handleAdminHolidaysPage)
	mux.HandleFunc("/admin/terms", handleAdminTermsPage)
	mux.HandleFunc("/admin/accounts", handleAdminAccountsPage)
	mux.HandleFunc("/admin/features", handleAdminFeaturesPage)
	mux.HandleFunc("/admin/notices", handleAdminNoticesPage)
	mux.HandleFunc("/admin/grading", handleAdminGradingPage)
	mux.HandleFunc("/admin/inactive", handleAdminInactivePage)
	mux.HandleFunc("/admin/milestones", handleAdminMilestonesPage)
	mux.HandleFunc("/admin/perf", handleAdminPerfPage)
	mux.HandleFunc("/admin/self-estimates", handleSelfEstimatesPage)

	// Member pages
	mux.HandleFunc("/training-log", handleTrainingLogPage)
	mux.HandleFunc("/messages", handleMessagesPage)
	mux.HandleFunc("/inbox", handleMemberInboxPage)
	mux.HandleFunc("/api/inbox", handleMemberInboxAPI)

	// Class types API
	mux.HandleFunc("/api/class-types", handleClassTypes)
	mux.HandleFunc("/api/programs", handlePrograms)

	// Layer 1b workflow routes
	mux.HandleFunc("/api/notices/publish", handleNoticePublish)
	mux.HandleFunc("/api/notices/edit", handleNoticeEdit)
	mux.HandleFunc("/api/notices/pin", handleNoticePin)
	mux.HandleFunc("/api/grading/proposals/decide", handleGradingDecide)
	mux.HandleFunc("/api/grading/config", handleGradingConfig)
	mux.HandleFunc("/api/grading/credit", handleGradingCredit)
	mux.HandleFunc("/api/grading/force-promote", handleGradingForcePromote)
	mux.HandleFunc("/api/grading/member-config", handleGradingMemberConfig)
	mux.HandleFunc("/api/grading/readiness", handleGradingReadiness)
	mux.HandleFunc("/api/grading/metric", handleGradingMetricToggle)
	mux.HandleFunc("/api/grading/notes", handleGradingNotes)
	mux.HandleFunc("/api/training-goals", handleTrainingGoals)
	mux.HandleFunc("/api/milestones", handleMilestones)
	mux.HandleFunc("/api/member-milestones", handleMemberMilestones)
	mux.HandleFunc("/api/member-milestones/dismiss", handleMemberMilestoneDismiss)
	mux.HandleFunc("/api/messages/read", handleMessageRead)

	// Layer 2: Spine API routes
	mux.HandleFunc("/api/themes", handleThemes)
	mux.HandleFunc("/api/clips", handleClips)
	mux.HandleFunc("/api/clips/promote", handleClipPromote)

	// Layer 2: Spine pages
	mux.HandleFunc("/themes", handleThemesPage)
	mux.HandleFunc("/library", handleLibraryPage)

	// Curriculum rotor system routes
	mux.HandleFunc("/curriculum", handleCurriculumPage)
	mux.HandleFunc("/api/rotors", handleRotors)
	mux.HandleFunc("/api/rotors/by-id", handleRotorByID)
	mux.HandleFunc("/api/rotors/activate", handleRotorActivate)
	mux.HandleFunc("/api/rotors/preview", handleRotorPreview)
	mux.HandleFunc("/api/rotors/themes", handleRotorThemes)
	mux.HandleFunc("/api/rotors/topics", handleTopics)
	mux.HandleFunc("/api/rotors/topics/reorder", handleTopicReorder)
	mux.HandleFunc("/api/rotors/topics/bump", handleTopicBump)
	mux.HandleFunc("/api/rotors/schedule/action", handleTopicScheduleAction)
	mux.HandleFunc("/api/votes", handleVotes)
	mux.HandleFunc("/api/curriculum/view", handleCurriculumView)
	mux.HandleFunc("/api/curriculum/overview", handleCurriculumOverview)

	// Calendar routes
	mux.HandleFunc("/calendar", handleCalendarPage)
	mux.HandleFunc("/api/calendar/events", handleCalendarEvents)

	// DevMode routes (admin-only impersonation)
	mux.HandleFunc("/api/devmode/impersonate", handleDevModeImpersonate)
	mux.HandleFunc("/api/devmode/restore", handleDevModeRestore)

	// Email system routes
	mux.HandleFunc("/admin/emails", handleAdminEmailsPage)
	mux.HandleFunc("/admin/emails/compose", handleAdminComposeEmailPage)
	mux.HandleFunc("/api/emails", handleEmailList)
	mux.HandleFunc("/api/emails/compose", handleEmailCompose)
	mux.HandleFunc("/api/emails/send", handleEmailSend)
	mux.HandleFunc("/api/emails/test-send", handleEmailTestSend)
	mux.HandleFunc("/api/emails/detail", handleEmailDetail)
	mux.HandleFunc("/api/emails/delete", handleEmailDelete)
	mux.HandleFunc("/api/emails/schedule", handleEmailSchedule)
	mux.HandleFunc("/api/emails/cancel", handleEmailCancel)
	mux.HandleFunc("/api/emails/reschedule", handleEmailReschedule)
	mux.HandleFunc("/api/emails/recipients/search", handleMemberSearchForEmail)
	mux.HandleFunc("/api/emails/recipients/filter", handleMemberFilterForEmail)
	mux.HandleFunc("/api/emails/recipients/by-session", handleRecipientsFilterBySession)
	mux.HandleFunc("/api/emails/recipients/by-class-type", handleRecipientsFilterByClassType)
	mux.HandleFunc("/api/schedules/recent-sessions", handleRecentSessions)
	mux.HandleFunc("/admin/emails/template", handleEmailTemplatePage)
	mux.HandleFunc("/api/emails/template", func(w http.ResponseWriter, r *http.Request) {
		if r.Method == "POST" {
			handleEmailTemplateSave(w, r)
		} else {
			handleEmailTemplateGet(w, r)
		}
	})
	mux.HandleFunc("/api/emails/preview", handleEmailPreview)
}
