$epics = @(
  @{t="Epic: §1 Foundation";b="Roles, permissions, member statuses, programs/classes/schedule hierarchy, terminology, and the cross-cutting list view pattern.`n`n### Subsections`n- [ ] §1.1 Roles & Permissions`n- [ ] §1.2 Member Statuses`n- [ ] §1.3 Programs, Classes & Schedule`n- [ ] §1.4 Terminology`n- [ ] §1.5 List View Pattern (US-1.5.1 through US-1.5.6)";m=1;l=@("type:epic","area:foundation","cross-cutting")},
  @{t="Epic: §2 Kiosk & Check-In";b="Locked kiosk mode, name-based check-in, session auto-select, multi-session, and un-check-in.`n`n### Subsections`n- [ ] §2.1 Kiosk Mode (US-2.1.1–US-2.1.3)`n- [ ] §2.2 Check-In by Name Search (US-2.2.1–US-2.2.4)`n- [ ] §2.3 Session Auto-Select (US-2.3.1–US-2.3.2)`n- [ ] §2.4 Multi-Session Check-In (US-2.4.1)`n- [ ] §2.5 Un-Check-In (US-2.5.1–US-2.5.2)";m=3;l=@("type:epic","area:kiosk")},
  @{t="Epic: §3 Attendance & Training Log";b="Attendance records with mat hours, historical views, training log (flight time), estimated hours, and self-estimates.`n`n### Subsections`n- [ ] §3.1 Attendance Records (US-3.1.1–US-3.1.2)`n- [ ] §3.2 Historical Attendance (US-3.2.1–US-3.2.2)`n- [ ] §3.3 Training Log (US-3.3.1–US-3.3.3)`n- [ ] §3.4 Estimated Training Hours (US-3.4.1–US-3.4.3)`n- [ ] §3.5 Member Self-Estimates (US-3.5.1–US-3.5.3)";m=4;l=@("type:epic","area:attendance")},
  @{t="Epic: §4 Grading & Belt Progression";b="IBJJF-aligned belt system, automatic stripe inference, term-based kids grading, belt icons, readiness lists, proposals, and admin overrides.`n`n### Subsections`n- [ ] §4.1 Belt Progression System (US-4.1.1–US-4.1.3)`n- [ ] §4.2 Stripe Inference (US-4.2.1–US-4.2.2)`n- [ ] §4.3 Term-Based Grading (US-4.3.1–US-4.3.3)`n- [ ] §4.4 Belt & Stripe Icons (US-4.4.1–US-4.4.3)`n- [ ] §4.5 Grading Readiness (US-4.5.1–US-4.5.3)`n- [ ] §4.6 Proposals & Promotions (US-4.6.1–US-4.6.3)`n- [ ] §4.7 Admin Overrides (US-4.7.1–US-4.7.3)";m=5;l=@("type:epic","area:grading")},
  @{t="Epic: §5 Curriculum Rotor System";b="Versioned curriculum rotors with concurrent themes, topic queues, auto-advance, coach ownership, and member preview.`n`n### Subsections`n- [ ] §5.1 Rotor Structure (US-5.1.1–US-5.1.3)`n- [ ] §5.2 Themes (US-5.2.1–US-5.2.2)`n- [ ] §5.3 Topics & Queues (US-5.3.1–US-5.3.4)`n- [ ] §5.4 Rotor Advancement (US-5.4.1–US-5.4.4)`n- [ ] §5.5 Rotor Versioning (US-5.5.1–US-5.5.3)`n- [ ] §5.6 Member Preview (US-5.6.1–US-5.6.2)";m=7;l=@("type:epic","area:curriculum")},
  @{t="Epic: §6 Topic Voting";b="Members vote on topics to influence curriculum. Successful votes bump the scheduled topic.`n`n### Subsections`n- [ ] §6.1 Viewing & Voting (US-6.1.1–US-6.1.3)`n- [ ] §6.2 Vote-Driven Bump (US-6.2.1–US-6.2.4)";m=7;l=@("type:epic","area:voting")},
  @{t="Epic: §7 Technical Library & Clips";b="YouTube clip tool, searchable library, clip promotion, and global mute.`n`n### Subsections`n- [ ] §7.1 Clipping Tool (US-7.1.1–US-7.1.2)`n- [ ] §7.2 Technical Library (US-7.2.1–US-7.2.2)`n- [ ] §7.3 Promote Clip (US-7.3.1)`n- [ ] §7.4 Global Mute (US-7.4.1)";m=9;l=@("type:epic","area:library")},
  @{t="Epic: §8 Communication";b="Notices, full email system via Resend, account activation, and coach observations.`n`n### Subsections`n- [ ] §8.1 Notices (US-8.1.1–US-8.1.4)`n- [ ] §8.2 Email System (US-8.2.1–US-8.2.22)`n- [ ] §8.3 Coach Observations (US-8.3.1–US-8.3.2)";m=8;l=@("type:epic","area:communication")},
  @{t="Epic: §9 Member Management";b="Digital onboarding, red flags, member list, inactive radar, archive/restore, coach management, schedule/holiday management.`n`n### Subsections`n- [ ] §9.1 Digital Onboarding (US-9.1.1–US-9.1.2)`n- [ ] §9.2 Red Flag (US-9.2.1–US-9.2.2)`n- [ ] §9.3 Member List (US-9.3.1–US-9.3.2)`n- [ ] §9.4 Inactive Radar (US-9.4.1–US-9.4.2)`n- [ ] §9.5 Archive/Restore (US-9.5.1–US-9.5.2)`n- [ ] §9.6 Coach Management (US-9.6.1)`n- [ ] §9.7 Schedule & Holiday (US-9.7.1–US-9.7.3)";m=6;l=@("type:epic","area:member-mgmt")},
  @{t="Epic: §10 Calendar & Goals";b="Club calendar with toggleable layers, program rotor calendar view, and personal goals.`n`n### Subsections`n- [ ] §10.1 Club Calendar (US-10.1.1–US-10.1.4)`n- [ ] §10.2 Program Rotor Calendar (US-10.2.1–US-10.2.3)`n- [ ] §10.3 Personal Goals (US-10.3.1–US-10.3.3)";m=10;l=@("type:epic","area:calendar")},
  @{t="Epic: §11 Advanced Study";b="Technical tagging, 4-Up comparative mode, predictive search, and research journal.`n`n### Subsections`n- [ ] §11.1 Technical Tagging (US-11.1.1)`n- [ ] §11.2 4-Up Mode (US-11.2.1)`n- [ ] §11.3 Predictive Search (US-11.3.1)`n- [ ] §11.4 Research Journal (US-11.4.1)";m=11;l=@("type:epic","area:study")},
  @{t="Epic: §12 Competition & Performance";b="Advice repository and scouting pipeline.`n`n### Subsections`n- [ ] §12.1 Advice Repository (US-12.1.1)`n- [ ] §12.2 Scouting Pipeline (US-12.3.1)";m=11;l=@("type:epic","area:competition")},
  @{t="Epic: §13 Business Operations";b="Xero/bank reconciliation, program ROI dashboard, digital wallet, and engagement formula.`n`n### Subsections`n- [ ] §13.1 Xero/Bank Reconciliation (US-13.1.1)`n- [ ] §13.2 Program ROI Dashboard (US-13.2.1)`n- [ ] §13.3 Digital Wallet (US-13.3.1)`n- [ ] §13.4 Engagement ROI Formula";m=11;l=@("type:epic","area:business")},
  @{t="Epic: §14 Data Privacy & Compliance";b="Audit logging, granular consent, right to be forgotten, data export, and data classification.`n`n### Subsections`n- [ ] §14.1 Audit Logging (US-14.1.1–US-14.1.2)`n- [ ] §14.2 Consent Management (US-14.2.1–US-14.2.3)`n- [ ] §14.3 Right to be Forgotten (US-14.3.1–US-14.3.3)`n- [ ] §14.4 Data Export (US-14.4.1)`n- [ ] §14.5 Data Classification";m=11;l=@("type:epic","area:privacy","privacy-impact")}
)

foreach ($e in $epics) {
  $json = @{title=$e.t; body=$e.b; milestone=$e.m; labels=$e.l} | ConvertTo-Json -Depth 3
  $result = $json | gh api repos/ptetau/workshop/issues --input - 2>&1
  $num = ($result | ConvertFrom-Json).number
  Write-Host "Created #$num : $($e.t)"
  Start-Sleep -Milliseconds 500
}
